### PR TITLE
Change from Pleco to Tanton

### PR DESCRIPTION
**Pull request by chase-mew**
Pleco is no longer maintained, it has outstanding issues and hasn't had a new contribution in two and half years.  

[Tanton](https://github.com/chase-manning/tanton) is a fork of Pleco that is backward compatable and actively maintained.  

This PR changes from using Pleco to using Tanton.

### CODE REVIEW

**Comment by chase-manning** [comment]
@LinusCDE PR for review when you have a moment 😄

**Comment by LinusCDE** [comment]
Hi,

this seems pretty interesting. But for now I'll probably wait since this fork has me a bit concerned.

I'm a bit confused why a project in the early stage should already be replaced in a lot of projects that use pleco. Sure pleco didn't have any contributions recently, but for now I don't see a reason to switch just yet. This honestly looks like a red flag to me. I didn't find anything that would look malicious, but I'm still surprised by this sudden fork.

I'm not active in the chess community, but this seems to be super fresh.

I also skimmed the changes done since the last commit on the pleco repo. The lion share of changes seem to be rustfmt, cleaning up / updating ci/cd stuff and renaming the project and often authors. So for now, this doesn't seem to change much at least. Apart from polishing (which wouldn't really matter to me) this seems to contain little things done regarding the "outstanding issues".

Overall creating a repo, polishing, creating a logo and then prompting users of it to switch before notable development has been done for a while seems kinda weird to me. I'll give you the benefit of the doubt, but will still like to wait and see what happens before I truely consider switching this over. For me, pleco currently has no issues need addressing for this app.

Seems there was also an issue created here: https://github.com/sfleischman105/Pleco/issues/140

This can probably serve as a good way to track changes or hear why this happen so quickly. If this change is purely politically motivated I probably don't really know how to act rn. People that are deeper involved in the chess community are probably better do decide here.

Will leave this PR open, but for now just look how this unfolds or why this even happened.

Further discussions are probably done best in the issue mentioned above, since this exact issue was opened for a couple of other apps using pleco that are probably asking themselves the same.

**Comment by chase-manning** [comment]
Thanks for the thoughtful review and feedback @LinusCDE 😄 

You're right in that there is very little benefit to changing at this time as it is a new fork. I will keep you updated on progress and let you know when there is more meaningful benefit to this migration.

Sorry if the sudden PR seemed weird or alarming. I can assure you there's nothing politically motivated or anything about it ha ha. I'm just quite passionate about continuing to grow and improve on Pleco and the work that Stephen did. However I haven't been able to contact him via email, and PRs are not being merged. So the best way I saw to drive it forward was to fork it to continue development. I thought a new name would be better to avoid a potentially confusing situation where there are two Plecos. And I thought that there was some nice benefit for projects having their dependencies actively maintained, hence the PRs.

Thanks for the feedback on the versioning! I wasn't aware of the guarantees implied by this, I'll look more into this and consider changing it 😄

**Comment by LinusCDE** [comment]
That is nice to know. Sorry for me being a bit alarmed then yesterday. Was pretty late for me and the circumstances confused me.

Your intentions seem good here, so my doubt seems unfounded.

As said, I'll probably just keep this pr floating for now and probably merge it later down the road. For now pleco is stable for our purpose and I didn't notice any features, which where missing for pleco at least from our use cases (correct me if I'm wrong here, @rmadhwal ).

Having a maintained version is overall better though, so we should merge this at some point to have up-to-date versions when a new release is made.

**Comment by rmadhwal** [comment]
I noticed that the repo has been deleted/taken down, are you giving up on the fork @chase-manning ?

**Comment by chase-manning** [comment]
@LinusCDE @rmadhwal Heya! 😄 

The fork was created because Pleco was unmaintained, and there was no communication from the owner at the time.
As of yesterday, I have been in contact with the repo owner. It has now been moved to an org based ownership and maintenance will continue on this core repo. The existing changes and improvements from Tanton will be merged into Pleco, and Pleco will continue to be the core Crate moving forward. 

We can close this PR, and apologies for the wasted time here.

**Pull request closed without merging**
