### PR TITLE
After a bot move, highlight the source and destination of the piece

### PR DESCRIPTION
**Pull request by edupont**
Note: This will highlight different squares when castling, due to the
way the castling move is implemented upstream. (Piece destination should
be the final square of the king, but the implementation uses the
original position of the rook instead).

### CODE REVIEW

**Comment by LinusCDE** [comment]
Nice idea! I already have some ideas to iterate on that (separate from/to graphics). It's a really nice addition indeed.

**Comment by LinusCDE** [comment]
@edupont What do you find better of these? I guess I will go with the second one but would like to hear your opinion.

&nbsp;

(In each the bot moves the knight last. The second one has a thicker line.)

**Comment by edupont** [comment]
I would prefer more emphasis on which piece has moved, rather than where it came from (although it is also relevant).

The line below the moved piece seems too thin for this purpose.


On October 5, 2020 5:08:04 PM UTC, "Linus K." <notifications@github.com> wrote:
>@edupont What do you find better of these? I guess I will go with the
>second one but would like to hear your opinion.
>
>width="45%">&nbsp;src="https://transfer.cosmos-ink.net/m5D79/2.jpg" width="45%">
>
>(In each the bot moves the knight last. The second one has a thicker
>line.)
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/LinusCDE/chessmarkable/pull/4#issuecomment-703764920

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by LinusCDE** [comment]
Good idea. On the "from" image I wanted to highlight with the small lines that the figure was "picked up" from there. I could probably change the icon in the middle to be thinner or otherwise less intrusive.

The problem I see is that the position a piece moved away from is empty, so there is place to add a icon. That's not really the case where the figure moved to.

I added the same thin lines for the "to" position in hopes they are easier seen.

Here is a idea for the "to" image that is more noticable as it isn't just "hiding" under the chess piece:



I also have some ideas on alternative "from" images.

In the first one I just removed the square which looks odd to me. The second one looks add as well imo.

&nbsp;

Using a circle also looks odd (though I didn't take the time to adjust the stripes size and perspective wise).


Personally, I would personally like to stay with the old "from" image here. For the "to" image I don't have better ideas atm. Even though the new "to" image here is probably easier to spot, I still quite like the one from the second image in my last reply.

What do you think @edupont ?

**Comment by edupont** [comment]
Disclaimer: I am not an expert in usability and design, and can only speak about my use case.
When I let the device "think" for a while, I like to be able to tell at a glance whether it is my turn or not, and for this I just need "any visible" indication about which move was made (because my memory is not good enough to remember the board between moves).
The PR I submitted allows me to do just this, but it is of course your call to make sure that the appearance suits your preferences. If it were my call, I would go for the second to last proposition:
- Reusing the same image for both squares
- Unintrusive way to just highlight a square

**Comment by LinusCDE** [comment]
For now, I'll leave my initial rework of the "from" icon and the rework of the "to" icon from my last reply.

I also added some status messages. This might well be what you wanted in the first place as well.

<sub>([Other images](https://transfer.cosmos-ink.net/lmvGz/ress.tar.gz))</sub>

**Comment by LinusCDE** [comment]
This issue is probably done. If you have other suggestions, I'm all ears.

The current state can be seen in the 3rd screenshot of the readme.

/remindme To close this issue if nothing happens in 1 month

**Comment by LinusCDE** [comment]
/remindme To close this issue if nothing happens in 1 month

**Comment by LinusCDE** [comment]
/remind me To close this issue if nothing happens in 1 month

**Comment by LinusCDE** [comment]
Wow. It's so late, it didn't even notice this was already a merged pr. I really need to get some sleep before I continue attempting to finish stuff that's already done. :laughing:

**Pull request merged**
